### PR TITLE
fix nrec for lua_createtable , and add test case.

### PR DESCRIPTION
**Pull request by ops-dev-cn**
fix nrec for lua_createtable , and add test case.

### CODE REVIEW

**Comment by ops-dev-cn** [comment]
I'm not clear with rebase you say. I just deleted the fork before,and fork a new one.
https://github.com/openresty/lua-nginx-module/pull/567 And is this one is ok?
https://github.com/openresty/lua-nginx-module/pull/560 What about this?

**Comment by agentzh** [comment]
@ops-dev-cn Yes, the base is now up to date. BTW, you can always run the following commands to sync and rebase:

```
cd /path/to/my/fork/of/lua-nginx-module
git remote add openresty git@github.com:openresty/lua-nginx-module.git
git fetch openresty
git co master
git pull -u openresty master  # sync my master with the official master
git co my-branch  # where my additions reside
git rebase master
git push -f   # this will automatically update the PR if it already exists.
```

And yeah, it's usually not a good idea to do development directly on the `master` branch, even of your own. Better create a branch with a descriptive name.

**Comment by agentzh** [comment]
@ops-dev-cn I've merged your commit into master with slight modifications in the commit log message. Thanks for your contribution!

**Comment by ops-dev-cn** [comment]
Got it. So nice of you.

**Pull request closed without merging**
