### PR TITLE
Fixes for SSL error reporting

### PR DESCRIPTION
**Pull request by ghedo**

### CODE REVIEW

**Comment by agentzh** [comment]
@ghedo I don't think we should pass `""` to `*err` since it's required to only read `*err` when the C functions return an error status code.

**Comment by ghedo** [comment]
Yeah, but avoiding a segfault (even if it's the user's fault) seems like a good thing to do anyway, also considering that the fix is so simple.

**Comment by agentzh** [comment]
@ghedo Nope, unlike Lua, this is the C land so there's no hand-holding. Setting `NULL` is also easier to catch misuses on the caller's side (segfaults) and it's also more consistent with other FFI C APIs defined in ngx_lua.

**Comment by ghedo** [comment]
Fair enough. The other two commits are valid (and separate) fixes Ithink, should I just remove the err initialization commit from this PR?

**Comment by agentzh** [comment]
@ghedo Yes, please. Thank you!

**Comment by ghedo** [comment]
Ok, done.

**Comment by agentzh** [comment]
@ghedo Just merged to master. Thanks!

**Pull request closed without merging**
