### PR TITLE
Add a api for get current nginx worker numbers

### PR DESCRIPTION
**Pull request by wangfakang**
hi @agentzh:
 Add a api about get current nginx worker numbers, may be it's very simply but i think it's useful sometimes(may be i was wrong :D).   Please review :）and Thx.

### CODE REVIEW

**Comment by doujiang24** [comment]
@wangfakang Yes, it's useful, but there is a similar PR #531 
Anyway, nice job :)

**Comment by wangfakang** [comment]
@doujiang24 :+1:  thank you and so sorry don't  find your pr, long before used it at our project  and free time today so pr. thx.

**Comment by doujiang24** [comment]
@wangfakang The PR is not mine, it's created by @membphis :)

**Comment by agentzh** [comment]
Closing this since it's a duplicate of #531.

**Pull request closed without merging**
