### PR TITLE
bugfix: fix build on Debian with LuaJIT 2.1

### PR DESCRIPTION
**Pull request by ghedo**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

### CODE REVIEW

**Comment by agentzh** [comment]
@ghedo Why don't you just explicitly specify the `LUAJIT_LIB` and `LUAJIT_INC` environments as mentioned in the official installation documentation of this module?

**Comment by ghedo** [comment]
Well, yeah, but this makes it work out of the box. Not a big deal for me, just thought this might be useful given that there are a bunch of similar lines above.

**Comment by agentzh** [comment]
@ghedo I'd like to stop that auto detection code from growing. It's hard to maintain and test :)

**Comment by ghedo** [comment]
Fair enough, closing then.

**Pull request closed without merging**
