### PR TITLE
bugfix: remove extra spaces at the end of the request field name

### LINKED ISSUE #2140: ngx.req.set_header(key, value ) in kong plugin should throw error for BWS ("bad" whitespace) in header key
### Current Behavior

Adding header `ngx.req.set_header("X-cnn-Service ", "")` to a plugin is causing the request to throw HTTP 400 error due to the additional trailing whitespace in header's Key. 
reference- [field-parsing](https://greenbytes.de/tech/webdav/rfc7230.html#field.parsing) according to rfc7230 **No whitespace is allowed between the header field-name and colon** . 
Due to a small leading/trailing whitespace mistake , much of the developers time is wasted to find this issue .

### Expected Behavior

Two ideas can be proposed
1) Trim the leading/trailing whitespace of the header before plugin execution.
2) Log the  error , that plugin execution failed for the request due to invalid header

### Steps To Reproduce

```markdown
Create a Plugin with the following in access.lua
`
local BasePlugin = require "kong.plugins.base_plugin"
local priorities = require "kong.plugins.priorities"

local plugin_name = "headers-plugin"

local KongHeadersHandler = BasePlugin:extend()

function KongHeadersHandler:new()
   KongHeadersHandler.super.new(self, plugin_name)
end

function KongHeadersHandler:access(conf)
  KongHeadersHandler.super.access(self)
  ngx.req.set_header("X-cnn-Service ", "")
end

KongHeadersHandler.PRIORITY = priorities[plugin_name]
KongHeadersHandler.VERSION = "0.0.1"

return KongHeadersHandler`
```

### Anything else?

kong version 1.1.2
lua version  Lua 5.1.4 
LuaJIT 2.1.0-beta3
nginx version: openresty/1.13.6.2
LuaRocks main command-line interface /opt/kong/luajit/bin/luarocks 3.2.1

### PR DESCRIPTION
**Pull request by lynch1981**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

According to RFC7230 second paragraph of section-[3.2.4] (https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.4).
No whitespace is allowed between the header field-name and colon.

I just remove the extra space at the end of the request field-name for user convenience.
Nginx won't complain about headers like this, so the response part does not need to be processed.
fix #2140

Sorry the previous PR was closed by mistake, so i make a new one

### CODE REVIEW

**Comment by zhuizhuhaomeng** [comment]
The header name will be escaped later. There are other invalid characters that need to be processed if we need to validate the header name.

**Comment by lynch1981** [comment]
I checked the test case(t/028-req-header.t) and found that unsafe characters include \r \n \t.
It might be better to remove all unsafe characters in header fields. your idea？

**Comment by zhuizhuhaomeng** [comment]
The header has been escaped here, so you don't need to remove the invalid characters.

```
ngx_int_t
ngx_http_lua_set_input_header(ngx_http_request_t *r, ngx_str_t key,
    ngx_str_t value, unsigned override)
{
    ngx_http_lua_header_val_t         hv;
    ngx_http_lua_set_header_t        *handlers = ngx_http_lua_set_handlers;
    ngx_int_t                         rc;
    ngx_uint_t                        i;

    dd("set header value: %.*s", (int) value.len, value.data);

    rc = ngx_http_lua_copy_escaped_header(r, &key, 1);
    if (rc != NGX_OK) {
        return NGX_ERROR;
    }

    rc = ngx_http_lua_copy_escaped_header(r, &value, 0);
    if (rc != NGX_OK) {
        return NGX_ERROR;
    }
```

**Comment by zhuizhuhaomeng** [comment]
The header has been escapsed here
```
ngx_int_t
ngx_http_lua_set_input_header(ngx_http_request_t *r, ngx_str_t key,
    ngx_str_t value, unsigned override)
{
    ngx_http_lua_header_val_t         hv;
    ngx_http_lua_set_header_t        *handlers = ngx_http_lua_set_handlers;
    ngx_int_t                         rc;
    ngx_uint_t                        i;

    dd("set header value: %.*s", (int) value.len, value.data);

    rc = ngx_http_lua_copy_escaped_header(r, &key, 1);
    if (rc != NGX_OK) {
        return NGX_ERROR;
    }

    rc = ngx_http_lua_copy_escaped_header(r, &value, 0);
    if (rc != NGX_OK) {
        return NGX_ERROR;
    }
```

**Comment by lynch1981** [comment]
Thank you for your explanation, 
but the thing is that if a programmer  types a blank in the header by mistake, the upstream server returns a 400 error even though it is escaped, and then he needs to spend some time debugging, and if he is not familiar with the http protocol, he will spend more time. that is what issue 2140 said.

**Comment by lynch1981** [comment]
So I think it's programmer-friendly to tolerate these minor mistake

**Comment by zhuizhuhaomeng** [comment]
The better way is throwing errors instead of silently removing the spaces of other invalid characters. 
Because it is a per-request operation, it will have an impact on the impact.
Therefore, we should reduce unnecessary operations.

**Comment by lynch1981** [comment]
@zhuizhuhaomeng so sorry for the late response as I've been busy settling in recently.
now i just add  logs in debug mode to  reduce unnecessary operations

**Review by zhuizhuhaomeng — APPROVED** [review]

**Comment by zhuizhuhaomeng** [comment]
@lynch1981 This PR cannot help the end user at all. So, I won't accept it.

**Pull request closed without merging**
