### PR TITLE
bugfix: let `balancer.recreate_request` API work for body data changed case

### PR DESCRIPTION
**Pull request by oowl**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

Context: https://github.com/openresty/lua-nginx-module/issues/2333

### CODE REVIEW

**Comment by oowl** [comment]
I am not sure if this is a fix or a feature.

**Review by zhuizhuhaomeng — APPROVED** [review]

**Comment by zhuizhuhaomeng** [comment]
@oowl  please add a test case to cover this bug.

**Comment by oowl** [comment]
@zhuizhuhaomeng CI is flaky, I am not sure why the plan number is not stable in our Perl test.

**Review by zhuizhuhaomeng — APPROVED** [review]

**Comment by zhuizhuhaomeng** [comment]
The test ran failed on my side.

**Pull request merged**
