### PR TITLE
Revert "bugfix: ngx.escape_uri: we did not escape URI reserved chars. #1124"

### PR DESCRIPTION
**Pull request by spacewander**
Commit f170505186ff61af36b3e126772b671793af9428 breaks the compatibility with RFC 3986. Here is two reasons:
1. Quote from RFC 3986 Section 2.2:
> A subset of the reserved characters (gen-delims) is used as
delimiters of the generic URI components described in Section 3

Note that RFC 3986 says 'a subset of the reserved characters
(gen-delims)', not all the reserved characters. The characters escaped
in that commit are 'sub-delims'. They are not required to be escaped
according to Section 2.2.

2. Refer to RFC 3986 "Appendix A.  Collected ABNF for URI", sub-delims
could be used as part of query and other components. This use case shows
that sub-delims are valid in some component of URI. Therefore, it would
be better if we don't escape them for URI component.

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

### CODE REVIEW

**Comment by agentzh** [comment]
@spacewander Is our behavior consistent with web browser's JavaScript encodeURIComponent()? This is the only thing I care.

**Comment by spacewander** [comment]
@agentzh 
encodeURIComponent doesn't escape `!~*'()`.

```javascript
> encodeURIComponent("!~*'()")
'!~*\'()'
```

**Comment by agentzh** [comment]
@spacewander Then it's good! I'll merge this.

**Comment by agentzh** [comment]
@spacewander Merged. Thanks!

**Pull request closed without merging**
