### PR TITLE
added an API for getting and setting the keepalive property of a request

### PR DESCRIPTION
**Pull request by aviramc**

### CODE REVIEW

**Comment by agentzh** [comment]
@aviramc Thank you for the update! Yeah, sometimes I found myself want this feature as well :) I'll look into this as soon as I can :)

**Comment by agentzh** [comment]
@aviramc Will you mind adding some test cases for this feature? Otherwise it looks good to me :)

**Comment by aviramc** [comment]
@agentzh , I've added some test cases

**Comment by StephanDollberg** [comment]
Any update on this?

**Comment by agentzh** [comment]
@StephanDollberg What's you use case of this? Maybe you should just manipulate the `Connection` request header via `ngx.req.set_header()` and `ngx.req.clear_header()`?

**Comment by josephcsible** [comment]
I'm in need of this feature as well.

@agentzh r->keepalive is set early enough that by the time you're far enough along to change the header that it's already set and won't be affected by changes to the header (or even by changes to connection_type).

**Comment by zhuizhuhaomeng** [comment]
I have decided to close this PR and use FFI to rewrite it if needed.

**Pull request closed without merging**
