### PR TITLE
feature: add ngx_http_lua_ffi_ssl_client_random.

### PR DESCRIPTION
**Pull request by xuruidong**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

### CODE REVIEW

**Comment by splitice** [comment]
For what purpose?

**Comment by xuruidong** [comment]
> For what purpose?

We need to verify the client and reject the untrusted client during the SSL handshake. The client needs to use the client random to generate a token.

**Comment by zhuizhuhaomeng** [comment]
https://app.travis-ci.com/github/openresty/lua-nginx-module/jobs/618525464#L1204
CI failed. Please resolve this issue.

**Comment by xuruidong** [comment]
> https://app.travis-ci.com/github/openresty/lua-nginx-module/jobs/618525464#L1204 CI failed. Please resolve this issue.

Hi,  @zhuizhuhaomeng , I can not get the ci log. How should I do?
image

**Comment by xuruidong** [comment]
> https://app.travis-ci.com/github/openresty/lua-nginx-module/jobs/618525464#L1204 CI failed. Please resolve this issue.

Hi @zhuizhuhaomeng , this issue has been resolved. I was wondering if you could help me review this PR and the PR at https://github.com/openresty/stream-lua-nginx-module/pull/338 . 
Thank you.

**Review by zhuizhuhaomeng — APPROVED** [review]

**Pull request merged**
