### PR TITLE
Update ngx_http_lua_common.h

### PR DESCRIPTION
**Pull request by hkmo**
ffi_write API 
see https://github.com/openresty/lua-nginx-module/issues/938

### CODE REVIEW

**Comment by agentzh** [comment]
@hkmo I don't see how your changes in this PR are related to #938. Please elaborate.

**Comment by hkmo** [comment]
@agentzh I added new constants for returned error codes by "ngx_http_lua_ffi_write()". 
But, we can use error messages instead that we pass back to the caller, similarly to other FFI functions like "balancer.set_current_peer()". I just wanted to avoid the overhead of error buffer.

**Comment by agentzh** [comment]
@hkmo Constant error strings have *zero* buffer overhead. They are already intern'ed Lua strings, just like integer constants.

**Comment by agentzh** [comment]
Also, constants defined in this modules' C header files are not visible nor usable by FFI and lua-resty-core anyway.

**Comment by agentzh** [comment]
@hkmo I think you should stick with the existing NGINX error codes like `NGX_DECLINED`, `NGX_ERROR`, `NGX_BUSY`, and etc. Too many detailed error codes make little sense in the real world and also complicates the caller code significantly.

**Comment by hkmo** [comment]
Didn't see these comments. I agree for the error codes. Already made these chsnges obsolete, andI was looking to cancel this PR #959.

**Pull request closed without merging**
