### PR TITLE
Add diagram of the order of directive execution to README

### PR DESCRIPTION
**Pull request by es**
I created a diagram to show the order in which directives are executed:

Lua Nginx Modules Directives

I figured others in the community would find it valuable as well so I added it to the README in https://github.com/openresty/lua-nginx-module/commit/fa8a2c52933ed40081d2b1b36e30c3afad18fcfb

r: @agentzh

### CODE REVIEW

**Comment by agentzh** [comment]
@es Nice chart! Will you please edit the `doc/LuaNginxModule.wiki` file instead? The markdown file was automatically generated from the the wiki file.

**Comment by es** [comment]
To include the image, would it be `[[File:https://cloud.githubusercontent.com/assets/2137369/15237510/7307da18-189c-11e6-8f6d-c07cf48abdb4.png|alt=Lua Nginx Modules Directives.]]`?

**Comment by agentzh** [comment]
@es Oh, this is indeed tricky. I'll take care of it myself. Sorry about that.

**Comment by agentzh** [comment]
@es Committed to master. Found a small thing though. Will you please change `xxx_by_lua_*` to `xxx_by_lua*` in the diagram? I've found the last underscore unneeded :)

**Comment by es** [comment]
What do you think about removing the asterisk as well to just `xxx_by_lua`?

**Comment by es** [comment]
Here's both, choose whichever one you like best:

lua nginx modules directives without underscore asterisk
lua nginx modules directives without last underscore

**Comment by agentzh** [comment]
@es Thanks! I prefer the `xxx_by_lua*` form. BTW, what tool did you use to create these diagrams?

**Comment by agentzh** [comment]
Committed the new version to master. Thanks!

**Comment by es** [comment]
No problem! I just used Google Drawings. Shared the doc with you to your gmail.

**Comment by agentzh** [comment]
@es Awesome! Thanks!

**Pull request closed without merging**
