### PR TITLE
bugfix: remove http2 hardcode limitation in `ngx.location` subrequest API

### PR DESCRIPTION
**Pull request by oowl**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

context: https://github.com/openresty/lua-nginx-module/issues/2243

### CODE REVIEW

**Comment by zhuizhuhaomeng** [comment]
@oowl would you please add some test cases to cover this change.

**Comment by oowl** [comment]
Yeah, i will. please wait for me running huge kong side integration test to verify http2 location capture case problem.

**Comment by zhuizhuhaomeng** [comment]
@oowl  any progress?

**Review by Water-Melon — APPROVED** [review]

**Comment by oowl** [comment]
@zhuizhuhaomeng Hi, I have been enable all http2 test in ci config. Can you help me take a look?
Note: Some test can not execute in http2 mode, so i disable it by `--- no_http2` config command for skip http2 test.

**Comment by oowl** [comment]
sister PR: https://github.com/openresty/test-nginx/pull/176

**Review by zhuizhuhaomeng — APPROVED** [review]

**Pull request merged**
