### PR TITLE
optimize: removed a duplicated include directive in ngx_http_lua_regex.c

### PR DESCRIPTION
**Pull request by thibaultcha**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

Sister PR at https://github.com/openresty/meta-lua-nginx-module/pull/42

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
This header is included in many files (https://github.com/openresty/lua-nginx-module/search?q=ngx_http_lua_pcrefix&unscoped_q=ngx_http_lua_pcrefix); removing it isn't an optimization IMO given the preproc guard :)

Just curious, are there specific build/compile problems that this PR resolves?

**Comment by p0pr0ck5** [comment]
>> This header is included in many files

> You will notice that in this case, the header is included twice, which isn't an issue per say, but was duplicated in this commit.

Dang, I need to open my eyes. Thanks.

**Comment by dndx** [comment]
This fix was merged in meta_lua https://github.com/openresty/meta-lua-nginx-module/commit/9a313da0009980f0b9afaa087c8589bc42365c1a already.

**Comment by agentzh** [comment]
Merged. Thanks!

**Pull request closed without merging**
