### PR TITLE
docs: remove mention of re.split() in TODO section

### PR DESCRIPTION
**Pull request by thibaultcha**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

### CODE REVIEW

**Comment by thibaultcha** [comment]
Should this list be updated to reflect an up-to-date "roadmap", with done items (if any), items that are not planed anymore (just like this patch wasn't not planed for ngx_lua anymore, but for lua-resty-core), and to reflect some sense of priority or thoughts on implementation to help contributors decide on what to tackle next (partly saying this as it is my current situation).

**Comment by agentzh** [comment]
@thibaultcha Yes, this TODO list should be updated. I'm just too busy to take care of every single bit of such things. You're welcome to submit such PRs when you find anything. Thanks.

**Comment by agentzh** [comment]
@thibaultcha Merged with edits in your commit log message. Thanks! (BTW, please follow the convention of existing commit log messages, thank you!)

**Comment by thibaultcha** [comment]
Cool. I'm just having a hard time writing past-tense commit messages, sorry. Will try to. 
I'm not entirely familiar with the current roadmap or priority between its items hence why my comment about it :)

**Comment by agentzh** [comment]
@thibaultcha Yeah, we'll try to do better on roadmaps and planning.

**Pull request closed without merging**
