### PR TITLE
rebase ssl-cert-by-lua on version 0.9.19

### PR DESCRIPTION
**Pull request by fvanniere**
This patch is the adaptation of  ssl-cert-by-lua to 0.9.19 based on your branch. There is no modification.

### CODE REVIEW

**Comment by agentzh** [comment]
Oh yeah, I'll look into this. Thanks! I'll have to run more tests on the merged version myself :)

**Comment by agentzh** [comment]
Just a quick note: I'll rebase the `ssl-cert-by-lua` branch to the upcoming v0.9.20 tag instead. Sorry for the delay on my side.

**Comment by twinge** [comment]
Sorry if this is already discussed somewhere else, but is there something holding back the ssl-cert-by-lua branch from merging into master?

**Comment by agentzh** [comment]
@twinge We'd like to upstream the patch supporting `ssl_certificate_by_lua*` for the nginx core before the merge. Also, we'd like to merge the `balancer_by_lua*` and `ngx.semaphore` features before the `ssl-cert-by-lua` merge. It takes time on our side due to stability concerns. Thanks for your understanding. Hopefully we can start the mass merging process soon after this Christmas (before that, we'd really like to kick a new OpenResty formal release out of the door).

**Comment by twinge** [comment]
Thanks for the quick response. OpenResty is awesome! :)

**Comment by agentzh** [comment]
@twinge Thanks :)

**Comment by agentzh** [comment]
I've just merged the master (v0.9.20) into the ssl-cert-by-lua branch. I'm closing this.

**Pull request closed without merging**
