### PR TITLE
bugfix: ngx.pipe: fixed a segfault when error_log is configured to us…

### PR DESCRIPTION
**Pull request by spacewander**
…e syslog.

Fix https://github.com/openresty/lua-resty-shell/issues/7.

I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

### CODE REVIEW

**Comment by spacewander** [comment]
The CI failure is caused by the connection timeout with iscribblet.org. Since this website is not maintained by ourselves, maybe we could remove it from the test files?

**Comment by spacewander** [comment]
The test case is submitted in https://github.com/openresty/lua-resty-core/pull/236

**Comment by spacewander** [comment]
I submitted a PR to remove iscribblet.org from the test suite: https://github.com/openresty/lua-nginx-module/pull/1492

**Comment by agentzh** [comment]
Need to rebase to the latest master to get CI green again.

**Pull request merged**
