### PR TITLE
Change to long brackets for regex examples

### PR DESCRIPTION
**Pull request by solugebefola**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

### CODE REVIEW

**Comment by solugebefola** [comment]
@agentzh here is the new PR with the modifications to the README

**Comment by thibaultcha** [comment]
Hi,

Thanks for looking into this. However, did you know this file is not to be manually edited? See the top of it, as it states:
```
<!---
Don't edit this file manually! Instead you should generate it by using:
    wiki2markdown.pl doc/HttpLuaModule.wiki
-->
```

The wiki2markdown.pl tool can be found in the openresty-devel repository: https://github.com/openresty/openresty-devel-utils

**Comment by solugebefola** [comment]
My bad, I will correct it.  Thanks for the heads up.

**Comment by zhuizhuhaomeng** [comment]
There is no better use of parentheses than quotes in these examples.
The PR has not been updated for a long time. So close it.

**Pull request closed without merging**
