### PR TITLE
move init_by_lua to init_module phase, ensure all shdict has inited

### PR DESCRIPTION
**Pull request by rainingmaster**
I hereby granted the copyright of the changes in this pull request
to the authors of this lua-nginx-module project.

can we move init_by_lua to ngx_http_lua_module's init_module phase,  ensure all shdict has inited. in this way, we can use third part shdict without initialize in ngx_http_lua_module.

### CODE REVIEW

**Comment by agentzh** [comment]
@rainingmaster Why don't you use ngx_http_lua's public C API to register your own shdict storage? It's much more reliable and elegant. See this example module in the test suite:

https://github.com/openresty/lua-nginx-module/tree/master/t/data/fake-shm-module

If you still believe there is a problem, please also add a test case to the existing test suite to cover it. Thank you.

**Comment by rainingmaster** [comment]
@agentzh I have see ngx_http_lua's public C API, it truely useful.
But in some case there is a problem: when we want to [share memary between lua-stream and lua-http](https://github.com/rainingmaster/lua-shdict-nginx-module), we can not ensure every `share memary` has initialized in `init_by_lua` phase. So I think mayby it is better to `share memary` more independence to lua-* ?
On the other hand, maybe the meaning of  `init master` in `ngx_module_t` is more appropriate to `init_by_lua` phase ? :)

**Comment by agentzh** [comment]
@rainingmaster Sharing shdicts between `ngx_stream_lua_module` and `ngx_http_lua_module` require a higher level module called `ngx_meta_lua_module`. Otherwise it's inherently unsafe. This has discussed before in the `ngx_stream_lua_module` github issues board. That's another topic.

And I don't think the `init_master` hook is actually used by grepping through the nginx source tree:

```console
agentzh@fedora64 ~/work/nginx-1.11.2 $ grep init_master -r src/
src/core/ngx_module.h:    ngx_int_t           (*init_master)(ngx_log_t *log);
```

**Comment by agentzh** [comment]
@rainingmaster I agree `init_module` is a better hook for `init_by_lua*` than the current choice.

**Comment by agentzh** [comment]
@doujiang24 @yangshuxin @helloyi Will you have a look at this patch please? Many thanks!

**Comment by rainingmaster** [comment]
@agentzh Sorry, I've wrote the phase wrong. I've use `init_module` in my patch

**Comment by doujiang24** [comment]
@agentzh LGTM :)

**Comment by rainingmaster** [comment]
because of nginx will run `exit(1)` while `init_module`, we can not move `init_by_lua*` to `init_module` phase. as https://github.com/openresty/lua-nginx-module/pull/1002 said.  : (

**Pull request closed without merging**
