### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by lancelijade**

### CODE REVIEW

**Comment by doujiang24** [comment]
@lancelijade It is better to squash the 2 commits in this PR into a single one :)

**Comment by lancelijade** [comment]
@doujiang24 The Github desktop do it automatically, and I don't know how to split them......

**Comment by agentzh** [comment]
@lancelijade Regarding the squash thing, please see http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by agentzh** [comment]
@lancelijade Anyway I'll merge your patch manually myself. No worries.

**Comment by agentzh** [comment]
@lancelijade Patch applied to master. Thanks for your contribution!

**Pull request closed without merging**
